# Generated by Django 2.1.3 on 2018-11-26 14:41

import app_nonsql.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedModelField(model_container=app_nonsql.models.Blog, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
